### ISSUE TITLE
Convert tests from legacy xUnit (`unittest` module) format to pytest

### ISSUE THREAD

**Issue by ntninja** [ipfs/py-datastore#3]
Currently all test use the old-fashioned xUnit-style `unittest` framework. To improve readability and simplicity of the test, they should be converted to pytest's `assert …`-syntax and fixtures.

**Comment by dheatovwil** [comment]
I will squeeze time to work on this, anyone interested can just email me and take over anytime.

**Comment by dheatovwil** [comment]
@alexander255  The tests are written for py2.7, should we create another issue to fix the failing tests first?

**Comment by AliabbasMerchant** [comment]
@dheatovwil I am fixing the tests also(py2 to py3), along with fixing the corresponding code.

**Comment by dheatovwil** [comment]
@AliabbasMerchant cool, I will work base on your branch then

**Comment by seeni-dev** [comment]
@dheatovwil are you working on this?

**Comment by seeni-dev** [comment]
It is better if we follow the same notation for test files. I think we should go with test_*.py.

**Comment by seeni-dev** [comment]
My work will be in this PR(https://github.com/ipfs/py-datastore/pull/9)

**Comment by seeni-dev** [comment]
@alexander255 @AliabbasMerchant We are using python3. Right ?

**Comment by seeni-dev** [comment]
> @alexander255 @AliabbasMerchant We are using python3. Right ?

Thanks Anyway.I verified the same myself with tox.ini and travis files.

**Comment by Seenivasanseeni** [comment]
@AliabbasMerchant Can you explain this line https://github.com/ipfs/py-datastore/blob/68afbd1a0e0d30d33a366ac2e7bc48adf68e8f30/datastore/filesystem/filesystem.py#L196?

**Comment by ntninja** [comment]
@Seenivasanseeni: Yes, we're targeting Python 3.7+ as that's what https://github.com/libp2p/py-libp2p targets (another important component for future `py-ipfs`). :slightly_smiling_face:

**Comment by dheatovwil** [comment]
@Seenivasanseeni On and off, yes.  As you can see the test case on master is failing as it is old, @AliabbasMerchant is upgrading the test (with unittest, I suppose), so I think it's best we make sure all tests are green before we switch to pytest?

**Comment by seeni-dev** [comment]
Sure.

**Comment by ntninja** [comment]
Done in #12 as a side-effect of porting to `@trio.testing.trio_test`

**Comment by ntninja** [comment]
This has been merged with #12 and is now fixed.
