### ISSUE TITLE
[DISCUSSION] Stuff to drop…

### ISSUE THREAD

**Issue by ntninja** [ipfs/py-datastore#5]
While looking through the codebase I found several abstractions that don't appear to do anything other than adding code. Items on the following list should be resolved by a decision to either *keep* or *drop* them. Tricky cases may also have their own issues referenced from there.

  * [x] `datastore.core.query.*` and maybe others from that module (**[UNDECIDED]**)
  * [x] `datastore.core.serialize.Serializer` and subclasses (see issue #4)

**Comment by ntninja** [comment]
Considering that we read and write binary streams from our backend implementations, I don't see any reason for keeping the whole `Query` interface at all. AFAICT this was included to create a cross-backend language for querying things like NoSQL-databases (MongoDB). Since we don't need that for `py-ipfs` (datastructures are decoded using IPLD from binary blobs), I suggest we drop this code entirely and use IPLD, where it makes sense, instead.

**Comment by ntninja** [comment]
I'd also like to nominate some stuff from `core/basic.py` for deletion:

  * `NullDatastore` as it clearly violates the library's constraints (use `DictDatastore` instead for testing)
  * `InterfaceMappingDatastore` won't be useful anymore as we switch to making the library async (#8)
  * `CacheShimDatastore` is redundant when we have `TieredDatastore` + `DictDatastore`

Also all the remaining datastore “shims” are likely better placed into extra modules instead of cluttering `core/basic.py`.

(Deleting code is so much fun! :grin:)

**Comment by ntninja** [comment]
I've dropped `InterfaceMappingDatastore` from my codebase as I don't see how it will be useful in an async/await library.

**Comment by AliabbasMerchant** [comment]
@alexander255 Yes. Lets delete all the things you mentioned above.

**Comment by ntninja** [comment]
#12 drops all of `InterfaceMappingDatastore`, `CacheShimDatastore` & `SymlinkDatastore`

**Comment by ntninja** [comment]
Summary: serialize is *keep* (see issue #4); query is *keep partially* (see issue #14)
