### ISSUE TITLE
[DISCUSSION] Indent using tabs?

### ISSUE THREAD

**Issue by ntninja** [ipfs/py-datastore#6]
This is a kind-of selfish request, but would it bother you if I unified all the indentation to using tabs and fix the remaining codestyle checks?

I know that 4-spaces is preferred by PEP-8 over tabs, but I like the extra flexibility of choosing the current indentation size based on context rather than hard-coding some arbitrary size.

Would that be OK for you? (@AlibabasMerchant)

**Comment by AliabbasMerchant** [comment]
I don't mind the change, but then wouldn't it be better to just stick to the standard PEP-8?

(Btw, you got my username wrong in the @mention 😄 )

**Comment by ntninja** [comment]
Damn! I never noticed that first `a`… :grin: 

> I don't mind the change, but then wouldn't it be better to just stick to the standard PEP-8?

The great thing about using tabs is that your average Python developer can view them as 4 spaces just like he always did. I actually view them as 4 spaces most of the time, but when working on small screen (3-way merge anybody?) reducing tab size to 2 (or even 1) can be very helpful.

On the other hand, I'm still sometimes have a hard time reading 2-space indented (Google convention) deeply nested JavaScript code – It's often very difficult for me not to mix up returns statements of different levels and such, but apparently most JS devs either don't care or prefer it that way? Had they chosen tabs, I would have to care. Similarly some developers may prefer other indents at other times and with tabs we don't need to argue over the indent size as it can be **both** at the same time.

^ So that's why I much prefer tabs for pretty much any use-case. Judge for yourself. :stuck_out_tongue_winking_eye:

**Comment by ntninja** [comment]
OK, we need a decision here. I did a lot of library restructuring for async/await and having first-class binary streams and it currently uses tabs.

Let's just vote on this then:

  * I said: We (or mostly me anyway) want this
  * @AliabbasMerchant says: Don't really care, but we should stick to the recommendations on PEP-8

@Seenivasanseeni please read the above and give your vote on this, thanks!

**Comment by seeni-dev** [comment]
I vote for async/await and PEP-8.

**Comment by ntninja** [comment]
Tabs or spaces?

**Comment by seeni-dev** [comment]
spaces

**Comment by adamjsawicki** [comment]
@alexander255 I suppose we can close this huh? 😎
