### ISSUE TITLE
Make this library async-friendly

### ISSUE THREAD

**Issue by ntninja** [ipfs/py-datastore#8]
Currently all of this library assumes synchronous I/O, considering that that is bad practice when interacting with the network datastore implementations and doesn't align with our goals for `py-ipfs`. Using [`anyio`](https://pypi.org/project/anyio/) for this would likely be “good enough” and not require us to bind ourselves to one specific event loop while the `asyncio` vs `trio` debate is still ongoing.

**Comment by ntninja** [comment]
Looks like `anyio` currently does not provide support for any kind of asynchronous I/O streams. Without those, using it will become quite verbose and add lots of boilerplate code.

After contemplating, I think going with `trio` for now should be OK. Once we have a working setup with one AIO library, translating the code to another shouldn't be too much work.

@AliabbasMerchant: Any opinions on this?

**Comment by AliabbasMerchant** [comment]
@alexander255 To be honest, I've never properly worked with any Async I/O library in Python. So no idea. Let me check out a few of the libraries.

**Comment by ntninja** [comment]
Bump. I've now converted the entire `py-datastore` core to async using `trio`, so far our dependence on `trio` is rather weak and changing the asyncio framework would mostly consist of renaming a few methods and changing some imports. But the more I convert the harder it will likely get, so it would be useful to have a decision very soon.

**Comment by AliabbasMerchant** [comment]
Lets go with ```trio```

**Comment by AliabbasMerchant** [comment]
@alexander255 Umm... (Did you forget to create a PR? Or is it still WIP?)

**Comment by ntninja** [comment]
Ok thanks! I must admit that my codebase right now has not only the async/await port, but also the complete ObjectDatastore/BinaryDatastore split – so it's gonna be quite a large PR, I fear.

I couldn't complete it yesterday though, as I got carried away adding typing annotations to some stuff that apparently [cannot](https://github.com/python/mypy/issues/7790) [be](https://github.com/python/mypy/issues/7191) [represented](https://github.com/python/mypy/issues/7791) by mypy at this time. (It was useful for finding a bunch of other inconsistencies before this however, so adding annotations wasn't *just* a waste of time like in this latest case involving cooperative multiple inheritance.)

I'll try to open a PR today though.

**Comment by AliabbasMerchant** [comment]
Type annotations are awesome!

**Comment by ntninja** [comment]
See #12

**Comment by adamjsawicki** [comment]
@alexander255 can this be closed because of #12?

**Comment by ntninja** [comment]
@Swixx: Yes, although the FS datastore provider hasn't been updated yet in master (see #13).

@AliabbasMerchant @Seenivasanseeni: May I have a review on #13 please? :slightly_smiling_face:
